on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  taro_release_job:
    runs-on: ubuntu-latest
    name: Taro Bundle Release
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Cache node_modules Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: |
          yarn
      - name: Lerna Bootstrap
        run: |
          yarn bootstrap
      - name: Release Taro React Native bundle
        uses: zhiqingchen/taro-react-native-release@v1
        with:
          workingdirectory: ./packages/taro-ui-demo-rn
          token: ${{ secrets.GITHUB_TOKEN }}
          appname: Taro-UI-Demo
          logo: https://pic5.58cdn.com.cn/nowater/fangfe/n_v25a185c1657984016926f26af591912c4.jpg
      - name: Upload Qr Image
        uses: actions/upload-artifact@v2
        with:
          name: bundle-qr-code
          path: |
            packages/taro-ui-demo-rn/release/qrcode/ios.png
            packages/taro-ui-demo-rn/release/qrcode/android.png